SocleMvc.Web/Controllers/ImportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Application.Etech.Core.Models;
using Socle.Data.Constantes;
using Application.Etech.Core.MVC;
using FileHelpers;
using Mapster;
using Socle.Applicatif.Personne;
using Socle.Applicatif.Region;
using Socle.Data.Dto.Personne;
using Socle.Data.Dto.Result;
using Socle.Data.Entities;
using Socle.Data.Enums;
using Socle.Service.Commune;
using Socle.Service.District;
using Socle.Service.Fokontany;
using Socle.Service.Fonction;
using Socle.Service.Province;
using Socle.Service.Region;

namespace SocleMvc.Web.Controllers
{
    public class ImportsController : BaseController
    {
        // GET: Imports
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadOfFile(HttpPostedFileBase fileUpload)
        {
            if (ModelState.IsValid)
            {
                if (fileUpload != null)
                {
                    if (fileUpload.FileName.EndsWith(".csv"))
                    {
                        try
                        {
                            var path = Server.MapPath(UtilityConstant.ImportOutputPath);
                            if (!Directory.Exists(path))
                            {
                                Directory.CreateDirectory(path);
                            }
                            var files = $"{DateTime.Now.ToString("yyyyMMddHHmmss")}-{Path.GetFileName(fileUpload.FileName)}";
                            //Directory.CreateDirectory(path);

                            Logger.Info($"Sauvegarde du fichier PRODUIT [{files}] dans [{path}]");
                            // file is uploaded
                            path = Path.Combine(path, files);
                            fileUpload.SaveAs(path);
                            Logger.Info($"Sauvegarde du fichier PRODUIT [{files}] => OK");

                            Logger.Info(">> Début Import PRODUIT ...");
                            var result = ImportCsv(path);
                            Logger.Info(">> Fin Import PRODUIT");

                            return View("RapportImport", result);
                        }
                        catch (Exception e)
                        {
                            Logger.Error("Erreur rencontré pendant l'import PRODUIT : ", e);
                        }
                    }
                    //return RedirectToAction("MessageTypeFichier", "Error");
                }
                //return RedirectToAction("MessageImportVide", "Error");
            }
            return RedirectToAction("Index", "Errors");
        }

        public ResultImportDto ImportCsv(string filename)
        {
            /*
             * - Lire fichier
             * - Si erreur format date ou autre, ajout dans liste erreur format
             * - Si doublon, ajout dans liste doublon OF
             * - Sinon, on insere dans la base
             * 
             * */
            var result = new ResultImportDto();
            var codes = new List<string>();
            try
            {
                using (var scope = ContextScopeFactory.CreateWithTransaction(IsolationLevel.ReadUncommitted))
                {
                    var engine = new DelimitedFileEngine<PersonneCsvDto>();
                    engine.Options.IgnoreFirstLines = 9;
                    // Enregistrer les erreurs et continue à traiter la prochaine ligne
                    engine.ErrorManager.ErrorMode = ErrorMode.SaveAndContinue;
                    //Traitement doublon
                    engine.AfterReadRecord += (eng, args) =>
                    {
                        var record = args.Record;
                        //Duplication au niveau Fichier et non pas dans Bdd, si dans BDD, on update l'enregistrement
                        if (codes.Any(x => x == $"{record.NomComplet}_{record.CIN}"))
                        {
                            Logger.Info($"Doublon CADENCE : NUM[{args.LineNumber}] -> LIGNES[{record.NomComplet}] -> CODE PRODUIT[{record.CIN}]");
                            //AddRecordTDuplicateList(result, record, args.LineNumber);
                            args.SkipThisRecord = true;
                        }
                        codes.Add($"{record.NomComplet}_{record.CIN}");
                    };
                    var datas = engine.ReadFileAsList(filename);
                    //total row
                    result.TotalRow = engine.TotalRecords;

                    //Traitement OF invalide
                    if (engine.ErrorManager.HasErrors)
                    {
                        Logger.Info($"Traitement de(s) {engine.ErrorManager.ErrorCount} ligne(s) érronée(s)");
                        AddRecordToErrorList(result, engine.ErrorManager.Errors);
                    }

                    //Traitement OF valide
                    if (datas != null && datas.Count > 0)
                    {
                        Logger.Info($"Début traitement de(s) {datas.Count} ligne(s) valide");

                        // var personnes = datas.Adapt<IList<Personne>>()?.ToArray();
                        // PersonneApplicatif.Instance.Add(personnes);
                        // scope.SaveChanges();
                        
                        
                        // TODO :: rh tsis ny district fa commune sy region ar province mis d las ts ajouté le info amzw

                        var provinces = ProvinceService.Instance.FindAll() ?? new List<Province>(); // use dapper
                        var regions = RegionService.Instance.FindAll() ?? new List<Region>();
                        var districts = DistrictService.Instance.FindAll() ?? new List<District>();
                        var communes = CommuneService.Instance.FindAll() ?? new List<Commune>();
                        var fokontanies = FokontanyService.Instance.FindAll() ?? new List<Fokontany>();
                        var fonctions = FonctionService.Instance.FindAll() ?? new List<Fonction>();

                        foreach (var personCsv in datas)
                        {
                            try
                            {
                                #region Province

                                var province = provinces?.FirstOrDefault(
                                    p => !string.IsNullOrEmpty(personCsv?.Province)
                                         && p.Nom.Contains(personCsv.Province));
                                if (province != null)
                                {
                                    // TODO
                                }
                                else
                                {
                                    province = new Province
                                    {
                                        Nom = personCsv.Province
                                    };

                                    ProvinceService.Instance.Add(province);
                                    provinces.Add(province);
                                }

                                #endregion

                                #region Region

                                var region = regions?.FirstOrDefault(
                                    p => !string.IsNullOrEmpty(personCsv?.Region)
                                         && p.Nom.Contains(personCsv.Region));
                                if (region != null)
                                {
                                    // TODO
                                }
                                else
                                {
                                    region = new Region
                                    {
                                        Nom = personCsv.Region,
                                        Province = province
                                    };

                                    RegionService.Instance.Add(region);
                                    regions.Add(region);
                                }

                                #endregion

                                #region Commune

                                var commune = communes?.FirstOrDefault(
                                    p => !string.IsNullOrEmpty(personCsv?.Commune)
                                         && p.Nom.Contains(personCsv.Commune));
                                if (commune != null)
                                {
                                    // TODO
                                }
                                else
                                {
                                    commune = new Commune
                                    {
                                        Nom = personCsv.Commune,
                                        Region = region
                                    };

                                    CommuneService.Instance.Add(commune);
                                    communes.Add(commune);
                                }

                                #endregion

                                #region District

                                var district = districts?.FirstOrDefault(
                                    p => !string.IsNullOrEmpty(personCsv?.District)
                                         && p.Nom.Contains(personCsv.District));
                                if (district != null)
                                {
                                    // TODO
                                }
                                else
                                {
                                    district = new District
                                    {
                                        Nom = personCsv.District,

SocleMvc.Web/Views/Imports/Index.cshtml
@model Socle.Data.Dto.Personne.PersonneDto

@{
    ViewBag.Title = "Import Excel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("UploadOfFile", "Imports", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div class="bot-btn-container">
        <h3 class="page-title" style="border-bottom: solid 0.5px #AAA; padding-bottom: 15px;">
            <span class="glyphicon  glyphicon-cloud-download"></span>&nbsp;
            Import du fichier csv
        </h3>

        <fieldset>
            <input type="file" name="fileUpload" id="filecsv" onchange="" style="display:inline;" />
            <input type="submit" value="Importer" class="btn btn-danger" />
        </fieldset>
    </div>
}

SocleMvc.Web/Views/Imports/RapportImport.cshtml
@using Socle.Data.Enums;
@model Socle.Data.Dto.Result.ResultImportDto
@{
    ViewBag.Title = "Import données antérieures";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-form">
    @{
        if (Model.Operation == OperationFlags.SUCCESS)
        {
            if (!Model.ImportWithError)
            {
                <div class="row text-message">
                    <div class="col-xs-12">
                        <h4>Import Cadence/Produit/Ligne réalisé avec succès.</h4>
                    </div>
                </div>
            }
            else
            {
                <div class="row text-message">
                    <div class="col-xs-12">
                        <h4>Import Cadence/Produit/Ligne réalisé. @Model.ValidRow / @Model.TotalRow ligne(s) traitée(s).</h4>
                    </div>
                </div>
            }
        }
        else if (Model.Operation == OperationFlags.ERROR)
        {
            <div class="row text-message">
                <div class="col-xs-12">
                    <h4>Erreur import.</h4>
                </div>
            </div>
        }
        else
        {
            <div class="row text-message">
                <div class="col-xs-12">
                    <h4>Aucune ligne traitée pendant l'import Cadence/Produit/Ligne.</h4>
                </div>
            </div>
        }
        if (Model.ImportWithError)
        {
            if (Model.ResultDoublons.Count > 0)
            {
                <label>
                    <h4>Les lignes suivantes n'ont pas pu être importées à cause des doublons du [code produit/lignes] :</h4>
                </label>

                var grid = new WebGrid(Model.ResultDoublons, canPage: false, canSort: false);
                @grid.GetHtml(
                    htmlAttributes: new { id = "dblTable" }, 
                    tableStyle: "table",
                    headerStyle: "header",
                    alternatingRowStyle: "alt",
                    selectedRowStyle: "select",
                    columns: grid.Columns(
                        grid.Column("NumeroLigne", "N° ligne"),
                        grid.Column("Ligne", "Ligne"),
                        grid.Column("CodeProduit", "Code produit"),
                        grid.Column("Produit", "Produit"),
                        grid.Column("Cadence", "Cadence"))
                    )
            }
            if (Model.ResultErreurFormats.Count > 0)
            {
                <label>
                    <h4>Les lignes suivantes n'ont pas pu être importées à cause des erreurs de formats :</h4>
                </label>

                var grid = new WebGrid(Model.ResultErreurFormats, canPage: false, canSort: false);
                @grid.GetHtml(
                    htmlAttributes: new { id = "erreurTable" }, 
                    tableStyle: "table",
                    headerStyle: "header",
                    alternatingRowStyle: "alt",
                    selectedRowStyle: "select",
                    columns: grid.Columns(
                        grid.Column("NumeroLigne", "N° ligne"),
                        grid.Column("Ligne", "Ligne"),
                        grid.Column("CodeProduit", "Code produit"),
                        grid.Column("Produit", "Produit"),
                        grid.Column("Cadence", "Cadence"),
                        grid.Column("MessageErreur", "Message d'erreur", style: "message-erreur")))
            }
        }
    }
</div>


<style>
    .message-erreur {
        width: 45%;
    }
</style>